"""Add provider_id to Review model (correct location)

Revision ID: 7d599eec59cf
Revises: 18e834780d51
Create Date: 2025-10-30 10:30:15.534372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d599eec59cf'
down_revision = '18e834780d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_reviews_provider_id', 'users', ['provider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_provider_id', type_='foreignkey')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###
